//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication460.SoapServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SoapServiceReference.ISoapService")]
    public interface ISoapService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/password", ReplyAction="http://tempuri.org/ISoapService/passwordResponse")]
        string password(string firstName, string lastName, int age);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/password", ReplyAction="http://tempuri.org/ISoapService/passwordResponse")]
        System.Threading.Tasks.Task<string> passwordAsync(string firstName, string lastName, int age);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/loginId", ReplyAction="http://tempuri.org/ISoapService/loginIdResponse")]
        int loginId(int age);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/loginId", ReplyAction="http://tempuri.org/ISoapService/loginIdResponse")]
        System.Threading.Tasks.Task<int> loginIdAsync(int age);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISoapServiceChannel : WebApplication460.SoapServiceReference.ISoapService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SoapServiceClient : System.ServiceModel.ClientBase<WebApplication460.SoapServiceReference.ISoapService>, WebApplication460.SoapServiceReference.ISoapService {
        
        public SoapServiceClient() {
        }
        
        public SoapServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoapServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string password(string firstName, string lastName, int age) {
            return base.Channel.password(firstName, lastName, age);
        }
        
        public System.Threading.Tasks.Task<string> passwordAsync(string firstName, string lastName, int age) {
            return base.Channel.passwordAsync(firstName, lastName, age);
        }
        
        public int loginId(int age) {
            return base.Channel.loginId(age);
        }
        
        public System.Threading.Tasks.Task<int> loginIdAsync(int age) {
            return base.Channel.loginIdAsync(age);
        }
    }
}
