//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication460.RestServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="results", Namespace="http://schemas.datacontract.org/2004/07/WebApplication460")]
    [System.SerializableAttribute()]
    public partial class results : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int login {
            get {
                return this.loginField;
            }
            set {
                if ((this.loginField.Equals(value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pass {
            get {
                return this.passField;
            }
            set {
                if ((object.ReferenceEquals(this.passField, value) != true)) {
                    this.passField = value;
                    this.RaisePropertyChanged("pass");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RestServiceReference.IRestService")]
    public interface IRestService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/password", ReplyAction="http://tempuri.org/IRestService/passwordResponse")]
        WebApplication460.RestServiceReference.results password(string firstName, string lastName, int age);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/password", ReplyAction="http://tempuri.org/IRestService/passwordResponse")]
        System.Threading.Tasks.Task<WebApplication460.RestServiceReference.results> passwordAsync(string firstName, string lastName, int age);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/loginId", ReplyAction="http://tempuri.org/IRestService/loginIdResponse")]
        WebApplication460.RestServiceReference.results loginId(int age);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/loginId", ReplyAction="http://tempuri.org/IRestService/loginIdResponse")]
        System.Threading.Tasks.Task<WebApplication460.RestServiceReference.results> loginIdAsync(int age);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRestServiceChannel : WebApplication460.RestServiceReference.IRestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestServiceClient : System.ServiceModel.ClientBase<WebApplication460.RestServiceReference.IRestService>, WebApplication460.RestServiceReference.IRestService {
        
        public RestServiceClient() {
        }
        
        public RestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplication460.RestServiceReference.results password(string firstName, string lastName, int age) {
            return base.Channel.password(firstName, lastName, age);
        }
        
        public System.Threading.Tasks.Task<WebApplication460.RestServiceReference.results> passwordAsync(string firstName, string lastName, int age) {
            return base.Channel.passwordAsync(firstName, lastName, age);
        }
        
        public WebApplication460.RestServiceReference.results loginId(int age) {
            return base.Channel.loginId(age);
        }
        
        public System.Threading.Tasks.Task<WebApplication460.RestServiceReference.results> loginIdAsync(int age) {
            return base.Channel.loginIdAsync(age);
        }
    }
}
